### ISSUE TITLE
타이머 종료 알림

### ISSUE THREAD

**Issue by leslie-kang-querypie** [sakang07/nyamodoro#3]
## Description
0분이 되어 타이머가 종료되면 이를 알리고 사이클 카운터가 올라가도록 구현 필요.

## Todo
- [x] 0분이 되어 한 사이클이 끝나면 다시 고양이가 울게 하여 알림.
- [x] 사이클 카운터가 1씩 올라가게 구현.
- [x] 사이클을 나타내는 이미지가 랜덤하게 삽입되도록 구현.
